import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { startDatabaseListener } from '@/lib/brevo/dbListener';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

if (typeof window === 'undefined') {
  startDatabaseListener().catch(console.error);
}

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "STR Market Map",
  description: "Generated by create next app",
    icons: {
    icon: [
       { url: '/favicon.png', type: 'image/png' },
    ]
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
 <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
